<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Image Processing Driver ("gd" or "imagick")
    |--------------------------------------------------------------------------
    */
    'driver' => env('IMAGE_RESIZER_DRIVER', 'gd'),

    /*
    |--------------------------------------------------------------------------
    | Default Output Quality (1 - 100)
    |--------------------------------------------------------------------------
    */
    'quality' => [
        'webp' => 82,
        'jpg'  => 85,
        'png'  => 90,
        'avif' => 75,
    ],

    /*
    |--------------------------------------------------------------------------
    | Default formats generated by the upload endpoint
    |--------------------------------------------------------------------------
    */
    'default_formats' => ['webp', 'jpg', 'png'],

    /*
    |--------------------------------------------------------------------------
    | Storage disk & upload directory
    |--------------------------------------------------------------------------
    */
    'disk' => env('IMAGE_RESIZER_DISK', 'public'),
    'upload_path' => 'uploads/images',

    /*
    |--------------------------------------------------------------------------
    | Upload limits
    |--------------------------------------------------------------------------
    | max_upload_kb : maximum uploaded file size in kilobytes.
    | max_pixels    : maximum width * height accepted (protects server memory).
    */
    'max_upload_kb' => 20480,
    'max_pixels'    => 40000000,

    /*
    |--------------------------------------------------------------------------
    | Upload endpoint
    |--------------------------------------------------------------------------
    | Add "auth" to the middleware list to restrict uploads to signed-in users.
    | Set "enabled" to false to register no routes and use the facade only.
    */
    'routes' => [
        'enabled'    => true,
        'prefix'     => 'image-resizer',
        'middleware' => ['web', 'throttle:30,1'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Frontend assets used by the Blade component
    |--------------------------------------------------------------------------
    | Point these to self-hosted files if you do not want to use a CDN.
    */
    'assets' => [
        'cropper_js'  => 'https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.6.1/cropper.min.js',
        'cropper_css' => 'https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.6.1/cropper.min.css',
    ],
];